"""RMC — Repeated Mention Cloze dataclass and .jsonl loader.

Each item corresponds to a 64-token window from a real corpus in which
one or more entity tokens appear ≥ 2 times.  All occurrences are masked;
methods must recover the gold token at every position jointly.

Two tracks:
  single_chain — one repeated entity; hard-equality THRML is the upper bound.
  multi_chain  — 2–4 distinct repeated entities; global hard-equality is
                 insufficient (must maintain separate identity chains).

Generated by experiments/build_rmc.py (frozen, deterministic, no ML).
Do not modify .jsonl files by hand.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Iterator

import torch


@dataclass
class RMCItem:
    item_id: str
    corpus: str        # 'owt_heldout' or 'wikitext103'
    track: str         # 'single_chain' or 'multi_chain'
    window_text: str   # decoded 64-token window for inspection
    masked_input_ids: torch.Tensor  # [L] with MASK_TOKEN_ID at mask_positions
    mask_positions: list[int]       # indices of masked tokens, sorted ascending
    gold_token_ids: list[int]       # gold token id at each mask position (same order)
    chain_labels: list[int]         # chain index per mask position (0 for single_chain)


def _parse(d: dict) -> RMCItem:
    return RMCItem(
        item_id=d["item_id"],
        corpus=d["corpus"],
        track=d["track"],
        window_text=d["window_text"],
        masked_input_ids=torch.tensor(d["masked_input_ids"], dtype=torch.long),
        mask_positions=d["mask_positions"],
        gold_token_ids=d["gold_token_ids"],
        chain_labels=d["chain_labels"],
    )


def load_items(path: str | Path) -> list[RMCItem]:
    """Load all items from a frozen .jsonl benchmark file."""
    items: list[RMCItem] = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if line:
                items.append(_parse(json.loads(line)))
    return items


def iter_items(path: str | Path) -> Iterator[RMCItem]:
    """Stream items from a frozen .jsonl benchmark file."""
    with open(path) as f:
        for line in f:
            line = line.strip()
            if line:
                yield _parse(json.loads(line))


def is_dev(item: RMCItem, dev_fraction: float = 0.2, seed: int = 42) -> bool:
    """Deterministic 20% dev split by item_id hash.

    Remaining 80% is the test split used after the Day-7 gate passes.
    """
    h = int(hashlib.md5(f"{seed}:{item.item_id}".encode()).hexdigest(), 16)
    return (h % 1000) < int(dev_fraction * 1000)
